### ISSUE TITLE
ERR_CONNECTION_REFUSED whith default config

### ISSUE THREAD

**Issue by uhessbai** [klessou/nuxt-firebase-docker#1]
I tried to launch the solution on docker following the instructions, but after launching the init.sh, a prompt quickly appear, but I can't reach localhost, do you know where it might come from? Thanks by advance

**Comment by klessou** [comment]
Hey uhessabai,

Thanks for trying this container.
I've just made some change, can you please try again and run the following commands:

- git clone git@github.com:klessou/nuxt-firebase-docker.git
- cd nuxt-firebase-docker/
- web-npm run generate && web-firebase deploy
- docker-compose run web vue init nuxt-community/starter-template .
- docker-compose up (without "-d" to see error messages :))

Best,

David

**Comment by uhessbai** [comment]
Hello again ! I re-downloaded the project and tried it on another computer, same thing for the prompt, 
more details : i use windows 10 and powershell, it seems to be a problem to use web-npm therefore i can use docker-compose : 
for docker-compose up it sends this : `
nuxt-firebase-docker | Starting project
nuxt-firebase-docker | npm ERR! path /code/node_modules/.staging/core-js-ba7bab57/library/modules
nuxt-firebase-docker | npm ERR! code ENOTEMPTY
nuxt-firebase-docker | npm ERR! errno -39
nuxt-firebase-docker | npm ERR! syscall rmdir
nuxt-firebase-docker | npm ERR! ENOTEMPTY: directory not empty, rmdir '/code/node_modules/.staging/core-js-ba7bab57/library/modules'
nuxt-firebase-docker |
nuxt-firebase-docker | npm ERR! A complete log of this run can be found in:
nuxt-firebase-docker | npm ERR!     /root/.npm/_logs/2018-05-12T01_50_31_310Z-debug.log
nuxt-firebase-docker | npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
nuxt-firebase-docker |
nuxt-firebase-docker | npm ERR! path /code/node_modules/.staging/core-js-ba7bab57/library/modules
nuxt-firebase-docker | npm ERR! code ENOTEMPTY
nuxt-firebase-docker | npm ERR! errno -39
nuxt-firebase-docker | npm ERR! syscall rmdir
nuxt-firebase-docker | npm ERR! ENOTEMPTY: directory not empty, rmdir '/code/node_modules/.staging/core-js-ba7bab57/library/modules'
nuxt-firebase-docker |
nuxt-firebase-docker | npm ERR! A complete log of this run can be found in:
nuxt-firebase-docker | npm ERR!     /root/.npm/_logs/2018-05-12T01_52_43_278Z-debug.log
nuxt-firebase-docker | Run project
nuxt-firebase-docker |
nuxt-firebase-docker | > project-docker@1.0.0 dev /code
nuxt-firebase-docker | > nuxt
nuxt-firebase-docker |
nuxt-firebase-docker | sh: 1: nuxt: not found
nuxt-firebase-docker | npm ERR! file sh
nuxt-firebase-docker | npm ERR! code ELIFECYCLE
nuxt-firebase-docker | npm ERR! errno ENOENT
nuxt-firebase-docker | npm ERR! syscall spawn
nuxt-firebase-docker | npm ERR! project-docker@1.0.0 dev: `nuxt`
nuxt-firebase-docker | npm ERR! spawn ENOENT
nuxt-firebase-docker | npm ERR!
nuxt-firebase-docker | npm ERR! Failed at the project-docker@1.0.0 dev script.
nuxt-firebase-docker | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
nuxt-firebase-docker |
nuxt-firebase-docker | npm ERR! A complete log of this run can be found in:
nuxt-firebase-docker | npm ERR!     /root/.npm/_logs/2018-05-12T01_52_44_048Z-debug.log
nuxt-firebase-docker exited with code 1`

**Comment by klessou** [comment]
Are you using a pre-existing project or did you run "docker-compose run web vue init nuxt-community/starter-template ." to start from scratch ?

**Comment by uhessbai** [comment]
I tried from scratch and acording to the output, the project has been builded

**Comment by klessou** [comment]
Ok,

Can you start from the beginning but try to close every programs that can listen to files in the app directory, for instance :
- Disable "Windows Defender - Real Time Protection"
- Disable your firewall
- Close your IDE
- Close every explorer windows
- ...
(maybe more ideas here : https://github.com/npm/npm/issues/17444 )

Then, if it's still does work can you send me results of these commands:
- docker-compose run web npm -v
- docker-compose run web npm config get registry
- docker-compose run web node -v
- ls -la app
- ls -la app/node_modules/

Best,

**Comment by uhessbai** [comment]
Sorry I closed the issue but forgot to thank you ! (A bit late but still 😸
